In [1]:
import numpy as np

In [2]:
#creating array from list with type float
a = np.array([[1,2,3],[5,8,7]], dtype ='float')
print ("Array created using passed list:\n",a)

Array created using passed list:
 [[1. 2. 3.]
 [5. 8. 7.]]


In [3]:
b = np.array((1,2,3))
print ("\nArray created using passed tuple:\n",b)


Array created using passed tuple:
 [1 2 3]


In [4]:
#creating a 3*4 array with all zeros
c = np.zeros((3,4))
print("\n",c)


 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#creat a constant value array of complex type
d = np.full((3,3),6,dtype ='complex')
print (d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [6]:
#create an array with random values
e = np.random.random ((2,2))
print("\nA",e)


A [[0.4089701  0.73646678]
 [0.10547686 0.01886422]]


In [7]:
#creat a sequence of integer
#from 0 to 30 with step 5
f = np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


In [8]:
g = np.linspace(0,5,10)
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [9]:
#reshaping 3*4 array to 2*2*3 array
arr = np.array([[1,2,3,4],
               [5,2,5,3],
               [1,3,5,3]])
newarr = arr.reshape(2,2,3)
print("\n",arr)
print("reshaped",newarr)


 [[1 2 3 4]
 [5 2 5 3]
 [1 3 5 3]]
reshaped [[[1 2 3]
  [4 5 2]]

 [[5 3 1]
  [3 5 3]]]


In [10]:
a = np.array([[1,2,3],[3,5,6],[9,6,0]])
print (a)
print(a.T)

[[1 2 3]
 [3 5 6]
 [9 6 0]]
[[1 3 9]
 [2 5 6]
 [3 6 0]]


In [11]:
#import panda as pd
import pandas as pd

#list of strings
lst = ['chota bheem' , 'chutki, raju', 'mukul', 'rajdeep']
df = pd.DataFrame(a)
print(df)

   0  1  2
0  1  2  3
1  3  5  6
2  9  6  0
